# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.10)
{

  description = "Dev environment for Traffic helper";

  inputs = {
    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1.*.tar.gz";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, flake-utils, nixpkgs }:
    let
      systems = [ "x86_64-linux" ];
      eachSystem = f: flake-utils.lib.eachSystem systems f;
    in eachSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        nodejs = pkgs.nodejs_21;
      in {
        packages.default = pkgs.callPackage ./default.nix { inherit nodejs; };

        devShells.default = pkgs.mkShell {

          packages = with pkgs; [ git prefetch-npm-deps ];
        };
      });
}
