openapi: "3.0.2"
info:
  title: Traffic Wise
  description: |-
    This is the API for traffic wise based on OpenAPI 3.0 specification..
  version: "1.0"
servers:
  - url: /v3

components:
  schemas:
    SafeRoutesResp:
      type: array
      items:
        $ref: "#/components/schemas/SingleResp"
    SingleResp:
      type: object
      properties:
        routes:
          type: array
          items:
            type: string
        risk:
          type: number
          format: float
        traveltime:
          type: number
          format: float
        distance:
          type: number
          format: float
    Coords:
      type: object
      properties:
        latitude:
          type: string
        longitude:
          type: string
    Preferences:
      type: object
      properties:
        vehicletype:
          type: string
          default: CAR
          enum:
            - PEDESTRIAN
            - BICYCLE
            - MOTORCYCLE
            - CAR
            - TRUCK
            - OTHER
        environment:
          type: string
          default: NORMAL
          enum:
            - IDEAL
            - NORMAL
            - ABNORMAL
            - DEVIANT
            - TROUBLESOME
            - EXTREME
        PathChoices:
          type: object
          properties:
            safety:
              type: number
              format: float
              default: 0.33
              minimum: 0
              maximum: 1
            time_of_day:
              type: number
              format: float
              default: 0.33
              minimum: 0
              maximum: 1
            distance:
              type: number
              format: float
              default: 0.33
              minimum: 0
              maximum: 1

    SafeRoutes:
      type: object
      properties:
        StartEnd:
          type: object
          properties:
            start_address:
              type: string
              example: "8 Sheldrake Drive Kanata"
            destination_address:
              type: string
              example: "40 Merivale Road, Ottawa"
        StartTime:
            type: object
            properties:
              day_of_week:
                type: string
                default: "MONDAY"
                enum:
                  - "MONDAY"
                  - "TUESDAY"
                  - "WEDNESDAY"
                  - "THURSDAY"
                  - "FRIDAY"
                  - "SATURDAY"
                  - "SUNDAY"
              time_of_day:
                type: string
                example: "1230"
        path_count:
          type: number
          minimum: 0
          maximum: 5
tags:
  - description: Find routes between your starting place and destination.
    name: Routes
  - description: Convert between latlong and addresses.
    name: Points
  - description: Custom preferences
    name: Preferences


paths:
  /prefer:
    description: Set custom preferenes for client.
    post:
      description: Provisioning user preferences
      tags:
      - Preferences
      operationId: setPreferences
      requestBody:
        required: true
        description: "JSON Settings"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Preferences"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Preferences"
      responses:
        "200":
          description: "Confirm Preferences are set"
          content:
              application/json:
                schema:
                  type: string
              application/xml:
                schema:
                  type: string



  /addresses:
    description: Get address from backend.Latitude and Longitude

    get:
      operationId: getAddressFromLatLong
      tags:
        - Points
      description: "get address in different format"
      parameters:
        - name: latitude
          in: query
          required: true
          schema:
            type: string
            example: "45.424721"
        - name: longitude
          in: query
          required: true
          schema:
            type: string
            example: "-75.695000"
      responses:
        "200":
          description: "All good"
          content:
            application/json:
              schema:
                type: string
            application/x-www-form-urlencoded:
              schema:
                type: string


  /latlong:
    get:
      operationId: getLatLongFromAddress
      description: get Latitude and Longitude from backend address
      tags:
        - Points

      parameters:
        - name: address
          in: query
          required: true
          schema:
            type: string
            example: "8 Sheldrake Drive Kanata"
      responses:
        "200":
          description: "All good"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Coords"
            application/xml:
              schema:
                $ref: "#/components/schemas/Coords"

  /saferoute:
    post:
      tags:
        - Routes
      description: "Get the routes"
      operationId: getSafeRoute
      parameters: []
      requestBody:
        required: true
        description: "JSON Settings"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SafeRoutes"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/SafeRoutes"
      responses:
        "200":
          content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/SingleResp"
              application/xml:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/SingleResp"

          description: Successful return of routes

